Build, deploy, and promote all services

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -17,7 +17,7 @@
 set -eEuo pipefail
 
 ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"
-SERVICE="server"
+ALL_SERVICES="apiserver,cleanup,server"
 
 if [ -n "$(git status --porcelain)" ]; then
   echo "✋ Uncommitted local changes!" >&2
@@ -29,12 +29,28 @@ if [ -z "${PROJECT_ID:-}" ]; then
   exit 1
 fi
 
+if [ -z "${SERVICES:-}" ]; then
+  echo "✋ Missing SERVICES!" >&2
+  exit 1
+fi
+
+if [ "${SERVICES}" == "all" ]; then
+  SERVICES=${ALL_SERVICES}
+  echo "🚧 Building all services! (${SERVICES})" >&2
+fi
+
 if [ -z "${TAG:-}" ]; then
   TAG="$(git rev-parse --short HEAD)"
   echo "🚧 Using generated tag! (${TAG})" >&2
 fi
 
-gcloud builds submit "${ROOT}" \
-  --project "${PROJECT_ID}" \
-  --config "${ROOT}/builders/build.yaml" \
-  --substitutions "_SERVICE=${SERVICE},_TAG=${TAG}" \
+IFS=',' read -ra SERVICES_ARR <<< "${SERVICES}"
+for SERVICE in "${SERVICES_ARR[@]}"; do
+  gcloud builds submit "${ROOT}" \
+    --project "${PROJECT_ID}" \
+    --config "${ROOT}/builders/build.yaml" \
+    --substitutions "_SERVICE=${SERVICE},_TAG=${TAG}" \
+    &
+done
+
+wait
diff --git a/scripts/promote b/scripts/promote
--- a/scripts/promote
+++ b/scripts/promote
@@ -17,7 +17,7 @@
 set -eEuo pipefail
 
 ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"
-SERVICE="server"
+ALL_SERVICES="apiserver,cleanup,server"
 
 if [ -z "${PROJECT_ID:-}" ]; then
   echo "✋ Missing PROJECT_ID!" >&2
@@ -27,6 +27,16 @@ fi
 if [ -z "${REGION:-}" ]; then
   echo "✋ Missing REGION!" >&2
   exit 1
+fi
+
+if [ -z "${SERVICES:-}" ]; then
+  echo "✋ Missing SERVICES!" >&2
+  exit 1
+fi
+
+if [ "${SERVICES}" == "all" ]; then
+  SERVICES="${ALL_SERVICES}"
+  echo "🚧 Building all services! (${SERVICES})" >&2
 fi
 
 if [ -z "${REVISION:-}" ]; then
@@ -39,7 +49,13 @@ if [ -z "${PERCENTAGE:-}" ]; then
   PERCENTAGE="100"
 fi
 
-gcloud builds submit --no-source \
-  --project "${PROJECT_ID}" \
-  --config "${ROOT}/builders/promote.yaml" \
-  --substitutions "_REGION=${REGION},_REVISION=${REVISION},_PERCENTAGE=${PERCENTAGE},_SERVICE=${SERVICE}" \
+IFS=',' read -ra SERVICES_ARR <<< "${SERVICES}"
+for SERVICE in "${SERVICES_ARR[@]}"; do
+  gcloud builds submit --no-source \
+    --project "${PROJECT_ID}" \
+    --config "${ROOT}/builders/promote.yaml" \
+    --substitutions "_REGION=${REGION},_REVISION=${REVISION},_PERCENTAGE=${PERCENTAGE},_SERVICE=${SERVICE}" \
+    &
+done
+
+wait
