HMAC API Keys, implement per-realm limiting on API keys (#192)
* Update go-limiter

* Implement per-realm rate limiting on API keys

* Remove comment

* Do not load scripts or anything on 500 page

* Parse nested templates

* Handle when flash is called with a nil session

* Add controller.Back for going "back"

* Support flash "warnings"

* Create middleware for altering request methods

* Enable tooltips globally

* Used a named logged for apikey

* Support enable/disable api keys

* Always sort apps by name

* Use transactions when running migrations

* Use IF EXISTS to bypass missing index removal

* Make apikey field length bigger

* Add configuration for API key HMAC keys

* Always set HMAC keys in tests

* Add v2 api keys

These new keys encode the realm into the key

* Add realm convenience methods for getting auth apps

* Add all CRUD operations for apikeys

* Ratelimit by realm instead of apikey

* Add migration and tests

* Fix responses for when content-type is unknown

* Fix log message

* The authorized app can be nil

Returning nil returns an untyped nil

* Remove js debug

* Automigrate to get new column

* Fix staticcheck errors

* Ensure migrations and services have the keys

* Fallout from rebase

diff --git a/scripts/migrate b/scripts/migrate
--- a/scripts/migrate
+++ b/scripts/migrate
@@ -33,6 +33,16 @@ if [ -z "${DB_ENCRYPTION_KEY:-}" ]; then
   exit 1
 fi
 
+if [ -z "${DB_APIKEY_DATABASE_KEY:-}" ]; then
+  echo "✋ Missing DB_APIKEY_DATABASE_KEY (e.g. projects/my-project/locations/us-east1/keyRings/my-kr/cryptoKeys/my-key)!" >&2
+  exit 1
+fi
+
+if [ -z "${DB_APIKEY_SIGNATURE_KEY:-}" ]; then
+  echo "✋ Missing DB_APIKEY_SIGNATURE_KEY (e.g. projects/my-project/locations/us-east1/keyRings/my-kr/cryptoKeys/my-key)!" >&2
+  exit 1
+fi
+
 if [ -z "${DB_PASS_SECRET:-}" ]; then
   echo "✋ Missing DB_PASS_SECRET (e.g. projects/my-project/secrets/my-secret/versions/1)!" >&2
   exit 1
@@ -55,5 +65,5 @@ fi
 
 gcloud builds submit "${ROOT}" \
   --config "${ROOT}/builders/migrate.yaml" \
-  --substitutions "_DB_CONN=${DB_CONN},_DB_ENCRYPTION_KEY=${DB_ENCRYPTION_KEY},_DB_NAME=${DB_NAME},_DB_PASS_SECRET=${DB_PASS_SECRET},_DB_USER=${DB_USER}" \
+  --substitutions "_DB_CONN=${DB_CONN},_DB_APIKEY_DATABASE_KEY=${DB_APIKEY_DATABASE_KEY},_DB_APIKEY_SIGNATURE_KEY=${DB_APIKEY_SIGNATURE_KEY},_DB_ENCRYPTION_KEY=${DB_ENCRYPTION_KEY},_DB_NAME=${DB_NAME},_DB_PASS_SECRET=${DB_PASS_SECRET},_DB_USER=${DB_USER}" \
   --project "${PROJECT_ID}"
